messages:
  prefix-ul: "<bold><red>U</red><white>L</white> <dark_gray>»</dark_gray></bold> <gray>"
  prefix: "<bold><red>U</red><white>L</white> <gray>{name}</gray> <dark_gray>»</dark_gray></bold> <gray>"
